[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde_cbor = "0.11.2"
serde_json = "1.0.140"
serde_yaml = "0.9.34"
toml = "0.8.20"
